### ISSUE TITLE
Apollo 서버와 Client 서버 간 통신 에러

### ISSUE THREAD

**Issue by raw20** [raw20/kokoafriends#46]
# 설명
`apollo` 서버에서 로그인 처리 과정 중 `client`에서 로그인 버튼을 누르면 인가코드를 `apollo` 서버에 넘기고 그 후 과정에서 `fetch 400 error`와 fetch 200이 동시 발생
 
![image](https://user-images.githubusercontent.com/62588402/221770990-75ffaecf-6828-4d74-bb50-6b8989073628.png)
![image](https://user-images.githubusercontent.com/62588402/221774255-6553da6c-9451-4377-9a36-ef02ec21eb22.png)
![image](https://user-images.githubusercontent.com/62588402/221774399-93a22d93-1321-4c61-a59a-3c10684c111b.png)

**Comment by alsrb3272** [comment]
Postman에서 서버 확인한 결과 토큰값을 불러오지 못 하고 html 코드로만 호출됌.
![124124](https://user-images.githubusercontent.com/81221555/221775000-c6e0602c-6eb9-4b80-a69b-5eb4c96bab3f.png)

**Comment by raw20** [comment]
`apollo` 서버 에서 처리하지말고 `client` 에서 처리하였고 REST API가 아닌 JS SDK를 이용하여 소셜로그인을 구현 하는 중
